version: '3.7'

services:

  web:
    image: node:18-alpine
    tty: true
    working_dir: /home/node/app
    command: "npm run watch"
    volumes:
      - ./backend:/home/node/app
    ports:
      - 4000:4000

  web_front:
    image: node:18-alpine
    tty: true
    working_dir: /home/node/app
    command: "npm run dev"
    volumes:
      - ./frontend:/home/node/app
    ports:
      - 3000:3000

  db_auth:
    container_name: db_auth
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2-alpine