import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";

import { SvgArrowLeft } from "@/assets";
import { Layout } from "@/components";
import { IrregularVersTable } from "@/components/IrregularVerbsTable";
import { TYPOGRAPHY } from "@/styles";
import { ButtonIcon } from "@/ui";

export default function VerbsTable() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Verbs-Table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Root>
          <IrregularVersTable />
          <StyledButton
            icon={<SvgArrowLeft />}
            text="Назад"
            onClick={() => router.back()}
          />
        </Root>
      </Layout>
    </>
  );
}

const Root = styled.main`
  width: 100%;
  position: relative;
  width: 100%;
  padding: 32px 86px;
  display: flex;
  justify-content: center;
`;

const StyledButton = styled(ButtonIcon)`
  position: absolute;
  left: 86px;
  flex-direction: row-reverse;
  ${TYPOGRAPHY.THICCCBOI_Bold_20px}
`;
